### ISSUE TITLE
T-Shirts?

### ISSUE THREAD

**Issue by andrewdamelio** [nodeschool/toronto#32] opened 2015-11-23 17:43 UTC
I've talked with a few people and it seems like having T-Shirts for mentors could be fun/helpful... easy to spot us in the crowds. 

I'm ok with doing it, just need a roll call of all required shirt cuts/sizes.

**Comment by kr1st1n4gr03g3r** [comment] 2015-11-23 17:56
I'd love to help design/illustrate these if you need someone. :)

**Comment by andrewdamelio** [comment] 2015-11-23 20:10
@gringogidget :heart:

**Comment by Rchristiani** [comment] 2015-11-23 20:20
I am in. Usually a xl for me. American appeal unisex cut?

**Comment by jeffjewiss** [comment] 2015-11-25 16:28
I'm in. I'm usually a medium. Yeah, would we need to do a bulk order for the cost to be reasonable?

Should we try to stick to our Toronto colours? It would be bright, but maybe a red shirt with white type? We'd definitely stand out then.

@gringogidget that would be amazing if you could design the shirts! :fireworks:

**Comment by Rchristiani** [comment] 2015-11-25 16:30
A like Heather Red colour with white text would be so nice!

**Comment by kr1st1n4gr03g3r** [comment] 2015-11-25 16:35
Yeah, I would totally love to. I forgot that you had a designer of that
logo so I didn't want to step on any toes :)

Very available if you want some artwork from me.

**Comment by andrewdamelio** [comment] 2015-11-25 16:38
@Rchristiani @jeffjewiss Yeah using our Toronto colours make sense, especially since we want to stand out :smile:

**Comment by andrewdamelio** [comment] 2015-11-25 20:23
Thoughts on something like this?

 <img width="428" alt="mockup" src="https://cloud.githubusercontent.com/assets/1683736/11408614/5cab9438-9388-11e5-94cf-0cbfd05ed475.png">

**Comment by Rchristiani** [comment] 2015-11-25 20:27
Yeah! I like it. Did try it with the hexagon around it?

**Comment by andrewdamelio** [comment] 2015-11-25 20:28
@Rchristiani I did, problem is i can't find a custom shirt provider that will match our RED colour, kind of throws off the look a bit, but i'll paste it here as a comparison.

**Comment by chrismendis** [comment] 2015-11-25 20:31
@andrewdamelio :heart: the white on red!

**Comment by kr1st1n4gr03g3r** [comment] 2015-11-25 20:32
I prefer the first one :)

**Comment by brenna** [comment] 2015-11-25 20:32
+1 for white on red, will probably also cost less to only print 1 colour

**Comment by Rchristiani** [comment] 2015-11-25 20:39
oh yeah! I was thinking just he white. but like a while hexagon border is what I meant.

But regardless I think it looks great!

**Comment by richgilbank** [comment] 2015-11-26 14:19
A++ would buy. I'll double check we can get the cost covered.

**Comment by darcyclarke** [comment] 2016-01-08 16:32
@andrewdamelio I would buy like 6 of those shirts. We should look at https://teespring.com/ to get these ordered. That way you don't have to foot the bill to get an order through.

**Comment by richgilbank** [comment] 2016-01-08 18:29
I think Shopify's fine with footing the bill for it if someone can get an estimate on cost

**Comment by andrewdamelio** [comment] 2016-01-08 18:31
can anyone recommend a good provider of shirts? :shirt:

**Comment by chrismendis** [comment] 2016-01-08 18:34
@andrewdamelio how about teespring.com, like @darcyclarke suggested?

**Comment by chrismendis** [comment] 2016-01-08 18:34
Oh, I see, because Shopify is fitting the bill! Thanks, @richgilbank!!!

**Comment by chrismendis** [comment] 2016-01-08 18:41
@andrewdamelio we got Format shirts made by [Source Screenprinting](http://sourcescreenprinting.com). We're very happy with them. Our contact is there can be reached at liam@sourcescreenprinting.com.

**Comment by Rchristiani** [comment] 2016-01-08 18:42
http://www.hardboiledinc.com/

I have used this company in the past for shirts. Not 100% sure how much. I can email today. Can I get a number?

**Comment by Rchristiani** [comment] 2016-01-08 18:45
Actually looking just at the site. It looks like it would be ~180 for 18 shirts. So lets say 200 just in case.

**Comment by darcyclarke** [comment] 2016-02-08 21:01
@richgilbank I can foot the bill initially to get the order in and then we can always just provide you with the receipt, correct?

**Comment by richgilbank** [comment] 2016-02-11 21:47
Soo, I ran with the $200 estimate and finally got it confirmed.
Looks like hardboiledinc.com has AA tri-blend down as 13.90/ea. plus a $35 setup charge for 1 colour. So, we're looking at 11 shirts. How many do we need? Thought we'd want a few more than that.

**Comment by Rchristiani** [comment] 2016-02-11 21:57
Should we maybe get doubles in some sizes, just to get extras? If it is not to $$$. Maybe make it a solid 20?

**Comment by richgilbank** [comment] 2016-02-11 22:16
Let's figure out how many we need and what sizes so we can move forward with this. I got $200 approved previously, but we can figure out what to do about the rest of it later - let's see if we can get them in time for the next event though. 

If everyone could please [fill this out](https://docs.google.com/forms/d/1ulRl69nIOcJ6HpaYvF_Z-Tmh5MFMITvxfxgTq9hig4o/viewform), we'll have something to work from. Please let me know if you have questions or concerns there. Thanks everyone!

**Comment by darcyclarke** [comment] 2016-03-24 14:32
@richgilbank I didn't get around to this yet, do you have any merch hook ups at Shopify? I looked into it last week but was having trouble finding someone that wouldn't just do bulk orders. Unfortunately, we all have different size/type needs and we're only getting 15-20 shirts (and they're all spread out between like 7 variations). 

I was thinking it may just be easier to run a TeeSpring campaign and get everyone to order their own, at a time, and then refund them.

I think @Rchristiani, you said you may know a place that could do different sizes/types for a half decent price. We're trying to stay around $15-20 a shirt.

**Comment by Rchristiani** [comment] 2016-03-24 14:40
Yeah @darcyclarke the place I mentioned above http://www.hardboiledinc.com/, it is worth emailing or calling and asking if we can do the sizes we want.

I worked with them in the past for a company I had, we got small runs of shirts. Like 25 total, s,m,l,xl. They are all screen printed, so they have that nice finish!

Let me know if you need me to email them, I don't have a working relationship with them, but I can look into it.

**Comment by Rchristiani** [comment] 2016-05-23 16:09
Closing since Rich dealt with this!

**Closed as completed by Rchristiani** 2016-05-23 16:09 UTC
